const Strings = {
    en:{
      title:'License Manager',
      name:'Name',
      email:'Email',
      role:'Role',
      actions: 'Actions',
      password:'Password',
      account:'Account',
      licenseType:'License type',
      modules:'Modules',
      licenseExpirationDate:'License expiration date',
      maintenanceSubscriptionExpirationDate: 'Maintenance subscription expiration date',
      numOfSeats:'Number of seats',
      confirmPassword:'Confirm password',
      organization:'Organization',
      avaliableSeats:'Avaliable seats',
      borrowedSeats: 'Borrowed seats',
      seatName:'Seat name',
      endDate:'End date',
      computerName:'Computer name',
      country:'Country',
      phone:'Phone',
      releaseDate:'Release date',
      notes:'Notes',
      activationTab: 'Activation',
      licenseRequestTab: 'License Request',
      licenseInformationTab: 'License Information',
      networkInformationTab: 'Network Information',
      customersMenu:'Customers',
      releasesMenu:'Releases',
      logMenu:'Log',
      usersMenu:'Users',
      rolesMenu:'Roles',
      generateLicense:'Generate license',
      serialNumber: 'Serial Number',
      nameReqMsg:'Please input your name!',
      userNameReqMsg:'Please input user name!',
      userNameReq:'Please input your username!',
      releaseNameReqMsg:'Please input release name!',
      emailValidationMsg:'The input is not valid e-mail!',
      emailReqMsg:'Please input your email!',
      userEmailReqMsg:'Please input user email!',
      roleReqMsg:'Please input user role!',
      releaseDateReqMsg:'Please input release date!',
      releaseNotesReqMsg:'Please input release notes!',
      passwordReqMsg:'Please input your password!',
      confirmPasswordReqMsg:'Please confirm your password!',
      matchPasswordMsg:'The two passwords that you entered do not match!',
      organizationReqMsg:'Please input your organization!',
      countryReqMsg:'Please input your country!',
      phoneReqMsg:'Please input your phone!',
      serialNumberReqMsg:'Please input your serial number!',
      confirmDeleteMsg:'Sure to delete?',
      editBtn:'Edit',
      addBtn:'Add',
      deleteBtn:'Delete',
      updateBtn:'Update',
      exportBtn:'Export',
      createBtn:'Create',
      viewBtn:'View',
      loginBtn:'Log in',
      logoutBtn:'Logout',
      addUserBtn:'Add user',
      addReleaseBtn:'Add release',
      updateUserBtn:'Update user',
      updateReleaseBtn:'Update release',
      cancelBtn:'Cancel',
      requestLicenseBtn:'Request license',
      activateBtn:'Activate',
      deactivateLicenseBtn:'Deactivate license',
      updateLicenseBtn:'Update license',
      searchPlaceholder:'input search text',
      userNamePlaceholder: 'Username',
      passwordPlaceholder: 'Password',
      selectRolePlaceholder: 'Select role',
      rememberMeCheck: 'remember me'

    }
  }
  export {Strings};